# Generated by Django 5.2.4 on 2025-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='Weight in grams (e.g., 0.120).', null=True),
        ),
    ]
