# Generated by Django 5.2.4 on 2025-10-24 14:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Main header image.', null=True, upload_to=blog.models.upload_to_header),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small preview image used in lists or cards.', null=True, upload_to=blog.models.upload_to_thumbnail),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Raw MDX content stored here.'),
        ),
    ]
